### ISSUE TITLE
[Feature] 공용 컴포넌트 구현

### ISSUE THREAD

**Issue by yoona1110** [FRONTLINE2024/bamboo-hy#1]
## 배경
동일한 기능을 수행하는 코드를 반복적으로 작성할 필요가 없고 유지 보수에 용이함

## ✅ TODO
- [x] heaer 구현
- [x] 게시글 item 구현
- [x] writing button 구현
- [x] main, sub button 구현
