### ISSUE TITLE
[Feature] msw 활용하여 api 모킹

### ISSUE THREAD

**Issue by yoona1110** [FRONTLINE2024/bamboo-hy#5]
## 배경
실제 서버 없이도 api 요청과 응답을 시뮬레이션 할 수 있기 때문에 백엔드가 준비되지 않은 상태에서도 웹이 제대로 동작하는지 확인하는데 도움을 줌

## ✅ TODO
- [x] msw 기본 세팅
- [x] 핸들러 파일 생성
- [ ] 회원 mock api
- [ ] 게시물 mock api
